version: "3.4"

services:

  hybrid-caching-redis:
    container_name: hybrid-caching-redis
    image: redis:6.2.3-alpine
    expose:
      - "6379"
  
  hybrid-caching-app:
    image: hybrid-caching-app:latest
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - hybrid-caching-redis
    links:
      - hybrid-caching-redis
    deploy:
      replicas: 3
  
  hybrid-caching-app-px:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '5000:80'
    depends_on:
      - hybrid-caching-app